function RB022Run510VCspot3baseline = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  RB022RUN510VCSPOT3BASELINE = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  RB022RUN510VCSPOT3BASELINE = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RB022Run510VCspot3baseline = importfile1("C:\Users\cmtmd\OneDrive - University of Leeds\PhD project infomation\Data\Code\MATLAB\Practise\RB022 Run 5 10V C spot 3_baseline.txt", [1, 1]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Feb-2021 21:52:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2"];
opts.SelectedVariableNames = "VarName2";
opts.VariableTypes = ["string", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
RB022Run510VCspot3baseline = readtable(filename, opts);

end